"""Synthetic-image intensity priors as REFERENCE data (provenance-tracked).

The SynthSeg generator paints each heart class around its REAL per-class intensity (blood bright, myo
dark) — the cue that makes synth transferable. Those per-class mean/std are derived reference values:
computed from the cohort's ground truth, traceable to it, reproducible. So they belong in the reference
store (`<data>/reference/synth_priors.yaml`) alongside the EF ranges — single-sourced + auditable in
the model card, not silently re-measured each run.

Build side lives here (it needs `load_to_gpu`); the read side is `core.reference.Reference` — core
can't import cardioseg, so the derivation sits in cardioseg and writes into core's reference dir.
Graceful: if the file is absent, the Generator falls back to measuring priors on the fly (same numbers,
just no provenance) — a fresh clone with no reference/ still trains.

Note: only the HEART classes (+bg) are global reference priors. The background TISSUE-TIER priors are
per-slice (derived from each slice's real intensity at synth time) — not global, so not stored here.
"""
from __future__ import annotations

from pathlib import Path

import torch
from omegaconf import OmegaConf

from core.labels import CLASSES                       # {1:('RV',..), 2:('LV-myo',..), 3:('LV-cav',..)}
from core.reference import reference_dir

from .synth import measure_class_stats

_BG = "background"


def _names(n_classes: int) -> dict[int, str]:
    """class int -> reference key. 0=background, 1..=CLASSES display names."""
    return {0: _BG, **{c: nm for c, (nm, _) in CLASSES.items()}}


def build_synth_priors(sources=None, inplane: float | None = None, out_dir=None) -> Path:
    """Measure per-class z-scored intensity (mean, std) from the labelled cohort and write
    `<data>/reference/synth_priors.yaml` with provenance. Computed from the same z-scored slices the
    model trains on, so the stored priors equal what on-the-fly measurement would give — just cited."""
    import polars as pl
    from core.config import DEFAULT_INPLANE
    from core.data import store, splits
    from .dataset import load_to_gpu

    inplane = DEFAULT_INPLANE if inplane is None else inplane
    df = store.load(sources, inplane=inplane).filter(pl.col("labelled"))
    X, Y = load_to_gpu(splits.paths(df), device="cpu")
    n = max(CLASSES) + 1
    means, stds = measure_class_stats(X, Y, n)
    names = _names(n)
    ds = sorted({d for d in df["dataset"].to_list() if d})
    based = f"processed/{store.param_key(inplane)} z-scored slices, sources={ds}, n_slices={X.shape[0]}"

    out: dict = {"synth_priors": {"intensity": {}}}
    for c in range(n):
        out["synth_priors"]["intensity"][names[c]] = {
            "value": [round(float(means[c]), 3), round(float(stds[c]), 3)],   # [mean, std], z-scored
            "source": "computed", "based_on": based, "extracted_by": "computed", "verified": True,
        }
    base_dir = Path(out_dir) if out_dir is not None else reference_dir()
    base_dir.mkdir(parents=True, exist_ok=True)
    path_out = base_dir / "synth_priors.yaml"
    header = ("# DERIVED synth intensity priors — generated by `python -m cardioseg.training.priors\n"
              "# --build` from the labelled cohort's z-scored slices. LOCAL (not committed). Each value\n"
              "# = [mean, std] in z-score units, verified=true (reproducible from the cohort).\n")
    path_out.write_text(header + OmegaConf.to_yaml(OmegaConf.create(out)))
    return path_out


def load_synth_priors(n_classes: int, device: str, strict: bool = True, ref=None
                      ) -> tuple[torch.Tensor, torch.Tensor] | None:
    """Per-class (means, stds) tensors from the reference store, or None if absent/incomplete (caller
    then measures on the fly). Honors the strict/verified rule of the reference store. `ref` injectable
    for tests; defaults to the live store."""
    if ref is None:
        from core.reference import Reference
        ref = Reference(strict=strict)
    names = _names(n_classes)
    vals = []
    for c in range(n_classes):
        v = ref.get("synth_priors", "intensity", names.get(c, str(c)))
        if v is None or len(v) != 2:
            return None
        vals.append(v)
    means = torch.tensor([m for m, _ in vals], dtype=torch.float32, device=device)
    stds = torch.tensor([s for _, s in vals], dtype=torch.float32, device=device)
    return means, stds


def _main():
    import argparse
    ap = argparse.ArgumentParser(description="Derive synth intensity priors -> <data>/reference/synth_priors.yaml")
    ap.add_argument("--build", action="store_true")
    ap.add_argument("--sources", nargs="*", default=None)
    a = ap.parse_args()
    if a.build:
        from core.obs import setup
        setup()
        p = build_synth_priors(sources=a.sources)
        print(f"wrote {p}\n{p.read_text()}")
    else:
        ap.print_help()


if __name__ == "__main__":
    _main()
